# Generated by Django 4.2.6 on 2023-10-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_contact_place_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
